const API_URL="https://digispark-v0hl.onrender.com", BUSINESS_PHONE="919236368939";

// Normal page scrolling
if(document.documentElement)document.documentElement.style.overflowY="auto";
if(document.body){document.body.style.overflowX="hidden";document.body.style.overflowY="auto";}

// Mobile navigation
const menuButton=document.querySelector(".menu-btn"),navLinks=document.querySelector(".nav-links");
if(menuButton&&navLinks){menuButton.addEventListener("click",()=>{navLinks.classList.toggle("open");menuButton.setAttribute("aria-expanded",navLinks.classList.contains("open")?"true":"false")});document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>{navLinks.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}));document.addEventListener("click",e=>{if(!navLinks.contains(e.target)&&!menuButton.contains(e.target)){navLinks.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}})}

const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();

// Make service cards fully clickable
document.querySelectorAll(".service-card").forEach(card=>{const link=card.querySelector('a[href*="service.html"]');if(!link)return;card.style.cursor="pointer";card.setAttribute("role","link");card.setAttribute("tabindex","0");card.addEventListener("click",e=>{if(!e.target.closest("a,button,input,select,textarea"))location.href=link.href});card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();location.href=link.href}})});

// Floating WhatsApp and Call buttons
(()=>{const s=document.createElement("style");s.textContent=`.ds-lead-actions{position:fixed;right:20px;bottom:20px;z-index:9999;display:flex;flex-direction:column;gap:10px}.ds-lead-btn{display:flex;align-items:center;gap:9px;padding:12px 16px;border-radius:999px;font:800 13px Inter,Arial,sans-serif;text-decoration:none;box-shadow:0 10px 30px rgba(0,0,0,.22);transition:.25s;border:1px solid rgba(255,255,255,.15)}.ds-lead-btn:hover{transform:translateY(-3px)}.ds-wa{background:#25D366;color:#fff}.ds-call{background:#111;color:#fff}.ds-lead-icon{width:28px;height:28px;display:grid;place-items:center;border-radius:50%;font-size:15px}.ds-wa .ds-lead-icon{background:rgba(255,255,255,.18)}.ds-call .ds-lead-icon{background:#f5b72b;color:#111}@media(max-width:600px){.ds-lead-actions{right:12px;bottom:12px}.ds-lead-btn{width:48px;height:48px;padding:0;justify-content:center}.ds-lead-btn span:last-child{display:none}}`;document.head.appendChild(s);const w=document.createElement("div");w.className="ds-lead-actions";w.innerHTML=`<a class="ds-lead-btn ds-wa" href="https://wa.me/${BUSINESS_PHONE}?text=${encodeURIComponent("Hello DigiSpark, I want to discuss a digital project.")}" target="_blank" rel="noopener"><span class="ds-lead-icon">☘</span><span>WhatsApp</span></a><a class="ds-lead-btn ds-call" href="tel:+${BUSINESS_PHONE}"><span class="ds-lead-icon">☎</span><span>Call Now</span></a>`;document.body.appendChild(w)})();

// Contact / enquiry form
const contactForm=document.getElementById("contactForm");
if(contactForm){const serviceField=document.getElementById("service");function addAfter(el,html){if(el&&el.parentElement)el.parentElement.insertAdjacentHTML("afterend",html)}addAfter(serviceField,`<label>Project Type<select id="projectType" required><option value="">Choose project type</option><option>New Project</option><option>Existing Website / Business</option><option>Monthly Marketing</option><option>One-Time Service</option><option>Other</option></select></label><label>Estimated Budget<select id="budget" required><option value="">Choose budget</option><option>Under ₹10,000</option><option>₹10,000 – ₹25,000</option><option>₹25,000 – ₹50,000</option><option>₹50,000 – ₹1,00,000</option><option>₹1,00,000+</option><option>Not decided yet</option></select></label>`);addAfter(document.getElementById("email"),`<label>Phone / WhatsApp<input type="tel" id="phone" placeholder="Enter your phone number" inputmode="tel" required></label>`);contactForm.addEventListener("submit",async e=>{e.preventDefault();const name=document.getElementById("name").value.trim(),email=document.getElementById("email").value.trim(),phone=document.getElementById("phone").value.trim(),service=document.getElementById("service").value,projectType=document.getElementById("projectType").value,budget=document.getElementById("budget").value,message=document.getElementById("message").value.trim(),fm=document.getElementById("formMessage"),btn=contactForm.querySelector('button[type="submit"]');if(!name||!email||!phone||!service||!projectType||!budget||!message){if(fm)fm.textContent="Please fill in all details.";return}if(fm)fm.textContent="Sending your enquiry...";if(btn){btn.disabled=true;btn.textContent="Sending..."}try{const r=await fetch(`${API_URL}/api/enquiries`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,phone,service,project_type:projectType,budget,message})}),d=await r.json();if(!r.ok)throw Error(d.message||"Unable to submit enquiry.");const wa=`https://wa.me/${BUSINESS_PHONE}?text=${encodeURIComponent(`Hello DigiSpark, I submitted an enquiry.\n\nName: ${name}\nEmail: ${email}\nPhone: ${phone}\nService: ${service}\nProject Type: ${projectType}\nBudget: ${budget}\nProject: ${message}`)}`,track=`client-status.html?token=${encodeURIComponent(d.trackingToken||"")}`;if(fm)fm.innerHTML=`✅ Enquiry #${d.enquiryId} submitted successfully!<br><a href="${track}" style="color:#a87508;font-weight:800">Track Enquiry Status →</a> &nbsp; <a href="${wa}" target="_blank" rel="noopener" style="color:#a87508;font-weight:800">Continue on WhatsApp →</a>`;contactForm.reset()}catch(err){console.error(err);if(fm)fm.textContent="❌ Unable to submit right now. Please try again or contact us on WhatsApp."}finally{if(btn){btn.disabled=false;btn.textContent="Send Enquiry →"}}})}

// Service-card reveal
const cards=document.querySelectorAll(".service-card");if("IntersectionObserver"in window&&cards.length){const observer=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.style.opacity="1";x.target.style.transform="translateY(0)";observer.unobserve(x.target)}}),{threshold:.15});cards.forEach(c=>{c.style.opacity="0";c.style.transform="translateY(20px)";c.style.transition="opacity .6s ease,transform .6s ease";observer.observe(c)})}

// ONLY the homepage banner is replaced; all other homepage sections remain the original ones.
(()=>{const p=location.pathname,hero=document.querySelector("main .hero");if(!hero||!(p.endsWith("/")||p.endsWith("/index.html")||p===""))return;document.body.classList.add("home-ref");if(!document.querySelector('link[data-digispark-reference]')){const l=document.createElement("link");l.rel="stylesheet";l.href="homepage-reference.css";l.dataset.digisparkReference="true";document.head.appendChild(l)}hero.innerHTML=`<div class="container hero-grid"><div class="hero-content"><div class="hero-badge"><span>🚀</span> DIGITAL SOLUTIONS THAT DRIVE RESULTS</div><h1>We Build, Grow &amp; Scale Your Business <span>Digitally</span></h1><p class="hero-text">From stunning websites to powerful marketing strategies, we provide end-to-end digital solutions to help your brand stand out and succeed online.</p><div class="buttons"><a href="services.html" class="btn primary">Explore Services <span>→</span></a><a href="#contact" class="btn secondary">▣ &nbsp; Get Free Consultation</a></div><div class="ref-trust"><div class="trust-plus">+</div><div class="trust-text"><strong>Trusted by 500+</strong><span>businesses worldwide</span></div></div></div><div class="hero-visual"><img class="hero-photo" src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85" alt="Digital business team working together"><div class="hero-photo-shade"></div><div class="ref-line"></div><div class="hero-brand-card"><div class="mark"><span>D</span><b>S</b></div><div class="name"><b>DIGI</b><strong>SPARK</strong></div><small>SPARK YOUR DIGITAL FUTURE</small></div><div class="floating-ref ref-web"><div class="ico">◎</div><div>Web<br>Development</div></div><div class="floating-ref ref-marketing"><div class="ico">⌁</div><div>Digital<br>Marketing</div></div><div class="floating-ref ref-seo"><div class="ico">↗</div><div>SEO<br><small>Optimization</small></div></div><div class="floating-ref ref-design"><div class="ico">✎</div><div>Graphic<br>Designing</div></div></div></div><div class="hero-statbar"><div class="hero-stat"><div class="stat-icon">☺</div><div><strong>500+</strong><span>Happy Clients</span></div></div><div class="hero-stat"><div class="stat-icon">▣</div><div><strong>850+</strong><span>Projects Completed</span></div></div><div class="hero-stat"><div class="stat-icon">🏆</div><div><strong>5+</strong><span>Years of Experience</span></div></div><div class="hero-stat"><div class="stat-icon">◉</div><div><strong>24/7</strong><span>Support Available</span></div></div></div>`;document.documentElement.style.overflowY="auto";document.body.style.overflowX="hidden";document.body.style.overflowY="auto"})();
